custom: ["https://www.patreon.com/tianheg", patreon.com]
custom: ["https://dun.mianbaoduo.com/@tianheg", mianbaoduo.com]
custom: ["https://afdian.net/@tianheg", afdian.net]
custom: ["https://paypal.me/tianheg?country.x=C2&locale.x=zh_XC", paypal.me]
