custom: ["https://www.patreon.com/tianheg", Patreon]
custom: ["https://dun.mianbaoduo.com/@tianheg", 面包多]
custom: ["https://afdian.net/@tianheg", 爱发电]
custom: ["https://paypal.me/tianheg?country.x=C2&locale.x=zh_XC", Paypal]
