custom: [Patreon, "https://www.patreon.com/tianheg"], ["https://dun.mianbaoduo.com/@tianheg", mianbaoduo.com], ["https://afdian.net/@tianheg", afdian.net]
custom: ["https://paypal.me/tianheg?country.x=C2&locale.x=zh_XC", paypal.me]
